### ISSUE TITLE
Update the link for Laboratory for Computational Social Systems (LCS2) on Home Page

### ISSUE THREAD

**Issue by BaaniLeen** [LCS2-IIITD/webpage#1]
As a member, 
I want to update the link for LCS2 mentioned on the home page, below the slider.

### Current status
It redirects to : http://lcs2.iiitd.edu.in/lcs2.iiitd.edu.in

### Suggested Change:
It should redirect to : http://lcs2.iiitd.edu.in instead.

**Comment by hridaydutta123** [comment]
Thanks for creating the issue. Please proceed with the PR.
